search/api/urls.py
from django.urls import path

from search.api.views import MakeSearchView

app_name = 'search_api'

urlpatterns = [
    path('search/', MakeSearchView.as_view(), name='search')
]

search/urls.py
from django.urls import path

from search.views import IndexView

app_name = 'search'

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

vector_search/urls.py
from django.contrib import admin
from django.urls import path, include

api_urls = [
    path('', include('search.api.urls'))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('api/', include(api_urls))
]

search/models.py
from django.db import models

search/api/views.py
import json

from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from search.utils import get_search_results


@method_decorator(csrf_exempt, name='dispatch')
class MakeSearchView(View):
    http_method_names = ['post']

    def post(self, request):
        data = json.dumps(dict(results=get_search_results(self.request.POST['q'])))
        return HttpResponse(data, status=200, content_type='application/json')

search/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'search/index.html'

templates/search/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поиск</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'search/css/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<div class="content mt-4">
    <div class="row search">
        <div class="input-group d-flex justify-content-center text-center">
            <div class="form-outline">
                <label class="form-label" for="search">Поиск</label>
                <input type="search" id="search" class="form-control"/>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div style="display: none" class="spinner-border mt-4" role="status">
            <span class="sr-only"></span>
        </div>
    </div>
    <div class="row mt-4 d-flex justify-content-center">
        <div class="results">

        </div>
    </div>
</div>

<script>

    let resultTile = `{% include 'search/result_tile.html' %}`;
    let results = $('.results');

    $("#search").keypress(function (event) {
        if (event.which == 13) {
            $.ajax({
                url: '{% url 'search_api:search' %}',
                method: 'POST',
                data: {
                    q: $('#search').val()
                },
                beforeSend: function () {
                    $('.spinner-border').css('display', 'block');
                    results.html('');
                },
                success: function (data) {
                    $.each(data.results, function (index, result) {
                        let json = JSON.parse(result);
                        results.append(resultTile.replace('$URL', json.url).replace('$TITLE', json.title).replace('$DISTANCE', json.distance));
                    })
                },
                complete: function () {
                    $('.spinner-border').css('display', 'none');
                }
            })
        }
    });
</script>
</body>

</html>

templates/search/result_tile.html
<div class="result-row mb-2">
    <span>
        <a target="_blank" href="$URL">$TITLE</a>
        Distance: $DISTANCE
    </span>
</div>